#!/bin/bash

echo "🔧 FIXING SESSION EXPIRATION ISSUE"
echo "===================================="
echo ""
echo "✅ Environment variables are correct:"
echo "   JWT_EXPIRES_IN=1d"
echo "   JWT_REFRESH_EXPIRES_IN=7d"
echo ""
echo "⚠️  IMPORTANT STEPS TO FIX:"
echo ""
echo "1. RESTART BACKEND SERVER"
echo "   - Stop current server (Ctrl+C)"
echo "   - Run: cd BACKEND && npm run dev"
echo ""
echo "2. CLEAR OLD TOKENS"
echo "   - Open browser DevTools (F12)"
echo "   - Go to Application > Local Storage"
echo "   - Delete 'token' and 'user' items"
echo "   OR"
echo "   - Just logout and login again"
echo ""
echo "3. LOGIN AGAIN"
echo "   - Go to /login"
echo "   - Enter credentials"
echo "   - New token will have 1 day expiration ✅"
echo ""
echo "Why this is needed:"
echo "- Old tokens were created with 15m expiration"
echo "- New tokens will have 1d expiration"
echo "- Must get new token by logging in again"
echo ""
echo "After these steps, your session will last 1 day! 🎉"
